USE DATABASE ITRA_DEMO;
USE SCHEMA PIPES;


ALTER TASK SERVER_INSTALL_EVENT_CHANGES SUSPEND;
ALTER TASK REFRESH_EVENTS_STREAM SUSPEND;
ALTER TASK DROP_DUPLICATES_FROM_JSON_RAW SUSPEND;


-- create task which drops duplicates from jso_raw table
CREATE OR REPLACE TASK drop_duplicates_from_json_raw
    WAREHOUSE = COMPUTE_WH
    AFTER SERVER_INSTALL_EVENT_CHANGES
    AS
INSERT OVERWRITE INTO ITRA_DEMO.raw_data.json_raw
(SELECT DISTINCT * FROM ITRA_DEMO.raw_data.json_raw);
    

-- create task which recreates events_stream
CREATE OR REPLACE TASK refresh_events_stream
    WAREHOUSE = COMPUTE_WH
    AFTER DROP_DUPLICATES_FROM_JSON_RAW
    AS
CREATE OR REPLACE STREAM pipes.events_stream ON TABLE ITRA_DEMO.raw_data.json_raw APPEND_ONLY=TRUE;


ALTER TASK SERVER_INSTALL_EVENT_CHANGES RESUME;
ALTER TASK REFRESH_EVENTS_STREAM RESUME;
ALTER TASK DROP_DUPLICATES_FROM_JSON_RAW RESUME;